FORMAT: 1A
HOST: http://arubaito.apiblueprint.org/

# arubaito

Arubaito is a simple API allowing client to get jobs.

## Jobs Collection [/jobs]

### List All Jobs [GET]

+ Response 200 (application/json)

        [
            {
                "id": "123",
                "title": "Ruby on Rails developer",
            }
        ]